### ISSUE TITLE
Combining multiple StaticGraphTemporalSignal objects into StaticGraphTemporalSignalBatch objects

### ISSUE THREAD

**Issue by petergroth** [benedekrozemberczki/pytorch_geometric_temporal#96]
Hi,

I've created a Dataset object which currently returns a single sequence (StaticGraphTemporalSignal) from a directory of many sequences. When feeding this to a DataLoader, I receive lists of length batch_size instead of batched objects. Is there a straightforward procedure of combining multiple StaticGraphTemporalSignal objects into a StaticGraphTemporalSignalBatch object? 
I have not found any examples of StaticGraphTemporalSignalBatch in use. 

Cheers.

**Comment by benedekrozemberczki** [comment]
Hi Peter, you can use the diagonal batching trick that is used to scale graph neural networks. I recommend reading the original PyTorch Geometric documentation. If you are willing to share the dataset we can write a tutorial based on your dataset. Bests, Benedek

**Comment by benedekrozemberczki** [comment]
What do you think @petergroth ?

**Comment by petergroth** [comment]
Hi - and thanks for your quick reply! That sounds like an interesting idea. I'm working with simple simulated data so it shouldn't be an issue. How should we proceed?

**Comment by petergroth** [comment]
The overall end-goal for me is to end up with a DataLoader-like structure with a variable batch_size so I can determine how many sequences I'd like to process simultaneously.  I imagine that each sequence of graphs will be saved locally as StaticGraphTemporalSignal objects. The tricky part is then designing a data structure which can combine a number of these as StaticGraphTemporalSignalBatch objects to iterate through one after the other. 

Does this make sense?

**Comment by Flunzmas** [comment]
I am a situation which seems to be very similar to that of @petergroth, meaning that I'd like use a custom DataLoader to automatically pack `Signal` objects loaded in parallel into the respective `Batch` objects and unpacking them on demand. Since this was closed without me seeing any apparent solution given or commit made, I figured I'd share my custom `DataLoader` class for PYGT in [this gist](https://gist.github.com/Flunzmas/5a5c8c8fd553609359704be3174db793).

The `DataLoader` class you can find there is a first attempt at directly extending the one of `pytorch-geometric` to handle lists of `Signal` objects by means of diagonal batching. However, there's things that might be worth improving (e.g. by the maintainers):

- Better typing and class hierarchies to improve code quality
- Check extensibility, e.g. graph attributes with arbitrary names
- Since the `SignalBatch` iterator returns `Batch` objects that are not constructed with `Batch.from_data_list()`, it's hard to reconstruct the individual graphs' `Data` objects (I have put my code to access the individual graphs in [this gist](https://gist.github.com/Flunzmas/0d35f67a3f5e73bdb952e1960b4b2388)).

I guess that providing such a `DataLoader` class could improve usability of this cool repo. @benedekrozemberczki if you like the code, I can submit a PR.

Cheers!

**Comment by kevinkorfmann** [comment]
@Flunzmas Thank you for sharing your dataloader. Seems to be exactly what I need as well, I am working with a large set of DynamicGraphTemporalSignal objects. And additionally the number of dynamic graphs  in each object is variable as well, though of a similar size. Do you think I can use your dataloader to batch them up or is your dataloader specific to a particular kind of signal?

**Comment by Flunzmas** [comment]
> @Flunzmas Thanks a lot for sharing your dataloader. Seems to be almost exactly what I need as well, I am working with a large set of DynamicGraphTemporalSignal (DGTS) objects. And additionally the number of dynamic graphs in each object is variable as well, though of a similar size. Do you have an idea of how to modify the dataloader to also make it work on a variable number of dynamic graphs in each DGTS object?

From my understanding, you have temporal sequences of varying length in your signal object - this means that the Batch objects created for the later timesteps are compositions of fewer graphs.
- In the gist provided, remove the length consistency check in line 41.
- Replace the list comprehension in line 45 by a loop that can assemble the batches per timestep t by taking extracting graphs from all signals that actually still hold graphs for t.

Dealing with the resulting batch objects later on is then your own responsibility.
