### ISSUE TITLE
RNN hidden state passing

### ISSUE THREAD

**Issue by jbgao** [benedekrozemberczki/pytorch_geometric_temporal#98]
First thank you all the developer for making this geometric temporal.  Very useful.  

I started learning the first example at https://pytorch-geometric-temporal.readthedocs.io/en/latest/notes/introduction.html#applications and traced the program.  I note that the RNN hidden state is not passed from one snap to the next snap as for the next snap the program always set H = NONE which means all zeros.  Thus it seems it is not a RNN.   

I might miss something here, however in each snap calculation I think the H shall be kept inside DCRNN.

Junbin

**Comment by benedekrozemberczki** [comment]
Yes it can be. It is an illustrative example with resetting the hidden states. Please look at the example in the paper.

**Comment by airalcorn2** [comment]
@benedekrozemberczki - I agree with @jbgao that the example in the documentation is confusing. RNNs maintain a hidden state across time steps, which is what distinguishes them from a standard feedforward neural network, so the example to me suggests the hidden state is being managed internally by `DCRNN`, but that's not actually the case. I also found the comment that "the final non-linearity is not integrated into the recurrent graph convolutional operation" confusing because many of the RNN models (including `DCRNN`) _do_ nonlinearly transform the inputs. Given these observations, I think a clearer example might look something like:

```python3
class RecurrentGCN(torch.nn.Module):
    def __init__(self, node_features):
        super(RecurrentGCN, self).__init__()
        self.recurrent = DCRNN(node_features, 32, 1)
        self.linear = torch.nn.Linear(32, 1)

    def forward(self, x, edge_index, edge_weight, prev_h):
        h = self.recurrent(x, edge_index, edge_weight, prev_h)
        y = self.linear(h)
        return y, h
```

and:

```python3
for epoch in tqdm(range(200)):
    cost = 0
    prev_h = None
    for time, snapshot in enumerate(train_dataset):
        (y_hat, prev_h) = model(snapshot.x, snapshot.edge_index, snapshot.edge_attr, prev_h)
        cost = cost + torch.mean((y_hat - snapshot.y) ** 2)
    cost = cost / (time + 1)
    cost.backward()
    optimizer.step()
    optimizer.zero_grad()
 ```
